config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Notifications::Engine => '/notifications'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: %i[new create]
  get '/auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :projects do
    resources :features, except: [:index]
  end
  resources :tasks, only: %i[create update destroy]
  resources :comments, except: %i[index show new]
end

app/models/user.rb
# frozen_string_literal: true

# Service to download ftp files from the server
class User < ApplicationRecord
  has_secure_password
  has_many :projects, dependent: :destroy
  has_and_belongs_to_many :features
  has_many :comments, dependent: :destroy

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: EMAIL_REGEX }

  def accessible_projects
    features.map(&:project).uniq
  end

  def has_feature_access?(feature)
    feature.users.include? self or self == feature.project.user
  end

  def has_project_access?(project)
    projects.include? project or accessible_projects.include? project
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Service to download ftp files from the server
class UsersController < ApplicationController
  def index; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, flash: { success: 'You have successfully signed up' }
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Service to download ftp files from the server
module UsersHelper
end

app/views/users/_show.html.erb
<h4>Hi, <%= current_user.name %>!</h4>
<br>
<%= link_to pluralize(Notification.unread_count(current_user), 'Notification'), notifications_path, class: "text-dark" %>
<br>  
<%= link_to 'My projects', projects_path, class: "font-weight-bolder"%>
<br>
<br>
<%= link_to 'Log out', logout_path, class: "btn btn-danger" %>

app/views/users/index.html.erb
<%if current_user %>
  <%= render 'show' %>
<% else %>

<div class="row">
  <div class="col-2"></div>
  <div class="col-6">
    <%= link_to 'Sign up', new_user_path, class: "btn btn-primary btn-block m-4" %>
    <%= link_to 'Log in', login_path, class: "btn btn-success btn-block m-4" %>
    <%= link_to 'Sign in using outlook', "/auth/microsoft_graph_auth", method: :post, class: "btn btn-primary btn-block m-4" %>
  </div>
  <div class="col-2"></div>
</div>
<% end %>

app/views/users/new.html.erb
<div class="m-3">
  <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-dark rounded", local: true, validate: true) do |f| %>
       
  <%= render 'shared/errors' %>

  <div class="form-group">
    <%= f.label :name, class: "text-light" %>
    <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a username" %>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "text-light" %>
    <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "text-light" %>
    <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
  </div>

  <div class="form-group">
    <%= f.submit("Sign up",class: "btn btn-success btn-lg") %>
  </div>
  <% end %>
</div>