config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Notifications::Engine => '/notifications'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: %i[new create]
  get '/auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :projects do
    resources :features, except: [:index]
  end
  resources :tasks, only: %i[create update destroy]
  resources :comments, except: %i[index show new]
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :features, dependent: :destroy
  belongs_to :user, foreign_key: 'user_id'

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Service to download ftp files from the server
include SessionsHelper
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :set_project, only: %i[show edit update destroy]
  def index
    @projects = current_user.projects
  end

  def show
    if params[:query]
      @project.features = Feature.where('ticket_id LIKE ?',
                                        "%#{params[:query]}%").or(Feature.where('title LIKE ?', "%#{params[:query]}%"))
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = session[:user_id]
    if @project.save
      redirect_to projects_path, flash: { success: 'Project successfully created.' }
    else
      render :new, flash: { error: 'Project not saved' }
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to projects_path, flash: { success: 'Project successfully updated' }
    else
      render :edit, flash: { error: 'Project not updated' }
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, flash: { notice: 'Project successfully destroyed ' }
  end

  private

  def project_params
    params.require('project').permit(:name, :user_id)
  end

  def require_login
    redirect_to login_path, flash: { notice: 'please login first' } unless logged_in?
  end

  def set_project
    @project = Project.find(params[:id])
    redirect_to root_path, flash: { danger: 'you are not authorized' } unless current_user.has_project_access?(@project)
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

# Service to download ftp files from the server
module ProjectsHelper
end

app/views/projects/_form.html.erb
  <%= form_for(@project, class: "shadow p-3 mb-3 bg-dark rounded", local: true, validate: true) do |f| %>
    <% if @project.errors.any? %>
      <h2>Errors: </h2>
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>  
    <% end %>

    <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a project name" %>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.submit("Save",class: "btn btn-success btn-lg") %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>My Project(s)</h1>
<% @projects.each do |project| %>
  <div>
   <%= link_to project.name, project, target: :_blank,class: "font-weight-bolder" %>
    <%= link_to  "edit", edit_project_path(project),class: "btn btn-outline-dark" %>
    <%= link_to  "destroy", project, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
  </div>
  <br>
<% end %>
<h5>Accessible Projects</h5>
<% current_user.accessible_projects.each do |project| %>
  <div>
    <% unless project.user == current_user%>
      <%= link_to project.name, project, target: :_blank,class: "font-weight-bolder" %>
    <% end %>
  </div>
<% end %>
<br>
<%= link_to 'Add Project +', new_project_path,  class: 'btn btn-success btn-lg'  %>

app/views/projects/new.html.erb
<div>
  <h4>Add your project here</h4>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li>
        <a class="current_link">Current</a>
      </li>
      <li>
        <a class="backlog_link">Backlog</a>
      </li>
      <li>
        <a class="icebox_link">Icebox</a>
      </li>
    </ul>
  </div>

  <div id="page-content-wrapper">
    <div class="m-3 d-flex justify-content-center">
      <%= form_tag(project_path, method: :get) do %>
        Feature: <%= text_field_tag :query, params[:query] %>
        <%= submit_tag 'Search' %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-lg-2">
        <a href="#menu-toggle" class="btn btn-primary" id="menu-toggle"> Menu </a>
      </div>


      <div class="col-lg-3 p-0">
        <div class="card current_card">
          <div class="card-header">
            Current Iteration
            <button type="button" class="close" aria-label="Close" id="current">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="card-body">
            <% @project.features.each do |feature| %>
              <% if feature.panel_name == "current" && current_user.has_feature_access?(feature) %>
                <div class="border m-3 p-3">
                  <b>Title:</b> <%= feature.title %>
                  <br>
                  <b>status:</b> <%= feature.status %>
                  <br>
                  <div class="m-3">
                    <%= link_to  "Show", [@project, feature], class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <br>
          <div class= "m-3" >
            <%= link_to  "+ Add Feature", new_project_feature_path(@project), class: "btn btn-success m-3" %>   
          </div>
        </div>
      </div>


      <div class="col-lg-3 p-0">
        <div class="card backlog_card">
          <div class="card-header">
            Backlog
            <button type="button" class="close" aria-label="Close" id="backlog">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="card-body">
            <% @project.features.each do |feature| %>
              <% if feature.panel_name == "backlog"  && current_user.has_feature_access?(feature) %>
                <div class="border m-3 p-3">
                  <b>Title:</b> <%= feature.title %>
                  <br>
                  <b>status:</b> <%= feature.status %>
                  <br>
                  <div class="m-3">
                    <%= link_to  "Show", [@project, feature], class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <br>
          <div class= "m-3" >
            <%= link_to  "+ Add Feature", new_project_feature_path(@project), class: "btn btn-success m-3" %>   
          </div>
        </div>
      </div>


      <div class="col-lg-3 p-0">
        <div class="card icebox_card">
          <div class="card-header">
            Icebox
            <button type="button" class="close" aria-label="Close" id="icebox">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="card-body">
            <% @project.features.each do |feature| %>
              <% if feature.panel_name == "icebox"  && current_user.has_feature_access?(feature) %>
                <div class="border m-3 p-3">
                  <b>Title:</b> <%= feature.title %>
                  <br>
                  <b>status:</b> <%= feature.status %>
                  <br>
                  <div class="m-3">
                    <%= link_to  "Show", [@project, feature], class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <br>
          <div class= "m-3" >
            <%= link_to  "+ Add Feature", new_project_feature_path(@project), class: "btn btn-success m-3" %>   
          </div>
        </div>
      </div>

    </div>
  </div>
  <%= link_to 'Back to projects ', projects_path, class: 'btn btn-danger' %>

</div>



<%= stylesheet_link_tag "sidenav" %>
<%= javascript_include_tag "sidenavscript.js" %>
<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/js/bootstrap-multiselect.js" %>

<%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/css/bootstrap-multiselect.css" %>