config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Notifications::Engine => '/notifications'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: %i[new create]
  get '/auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :projects do
    resources :features, except: [:index]
  end
  resources :tasks, only: %i[create update destroy]
  resources :comments, except: %i[index show new]
end

app/models/feature.rb
# frozen_string_literal: true

# Service to download ftp files from the server
class Feature < ApplicationRecord
  enum status: %i[unstarted started completed delivered]
  enum panel_name: %i[current backlog icebox]

  has_many :tasks, dependent: :destroy
  belongs_to :project
  has_one_attached :file
  has_and_belongs_to_many :users
  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: { case_sensitive: false, scope: :project_id }
  validates :description, presence: true
  validates :status, presence: true
  validates :panel_name, presence: true

  after_commit :create_notifications, on: :update
  has_many :sent_notifications, class_name: 'Notification', foreign_key: :target_id, dependent: :destroy
  def create_notifications
    users.each do |user|
      Notification.create(notify_type: 'feature', user: user, target: self)
    end
  end
end

app/controllers/features_controller.rb
# frozen_string_literal: true

# Service to download ftp files from the server
include SessionsHelper
class FeaturesController < ApplicationController
  before_action :require_login
  before_action :set_project
  before_action :set_feature, only: %i[show edit update destroy]
  before_action :set_user, only: %i[new create edit update]
  def new
    @feature = @project.features.build
  end

  def create
    @feature = @project.features.build(feature_params)
    @feature.ticket_id = Faker::Bank.account_number(digits: 8)
    @feature.users << User.find(params[:users]) unless params[:users].nil?
    if @feature.save
      redirect_to project_path(@project), flash: { success: 'new feature added' }
    else
      render :new, flash: { error: 'feature not saved' }
    end
  end

  def show
    @task = Task.new
    @tasks = @feature.tasks
    @comment = Comment.new
    @comments = @feature.comments
    @usernames = @feature.users.pluck(:name).to_json.html_safe
  end

  def edit; end

  def update
    @feature.users.clear
    @feature.users << User.find(params[:users]) unless params[:users].nil?
    @old_status = @feature.status
    if @feature.update(feature_params)
      send_feature_status_change_email
      redirect_to project_path(@project), flash: { success: 'feature updated successfully' }
    else
      render :edit
    end
  end

  def destroy
    @feature.destroy
    redirect_to project_path(@project), flash: { notice: 'Feature was successfully destroyed.' }
  end

  private

  def feature_params
    params.require('feature').permit(:title, :description, :panel_name, :project_id, :file, :status)
  end

  def set_feature
    @feature = @project.features.find(params[:id])
    redirect_to root_path, flash: { notice: 'you are not authorized' } unless current_user.has_feature_access?(@feature)
  end

  def set_project
    @project = Project.find(params[:project_id])
    redirect_to root_path, flash: { notice: 'you are not authorized' } unless current_user.has_project_access?(@project)
  end

  def set_user
    @users = User.all
  end

  def send_feature_status_change_email
    if @feature.status != @old_status
      @feature.users.each do |user|
        FeatureMailer.with(feature: @feature, user: user).feature_status_updated.deliver_later
      end
    end
  end

  def require_login
    redirect_to login_path, flash: { notice: 'please login first' } unless logged_in?
  end
end

app/helpers/features_helper.rb
# frozen_string_literal: true

# Service to download ftp files from the server
module FeaturesHelper
end

app/views/features/_form.html.erb
<%= form_with(model: [@project, @feature], local: true, validate: true) do |f| %>
    <% if @feature.errors.any? %>
      <h2>Errors: </h2>
      <ul>
        <% @feature.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>  
    <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Enter your title" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control shadow rounded", placeholder: "Enter description" %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :project_id, class: "form-control shadow rounded" %>
  </div> 

  <div class="form-group">
    <%= f.label :panel_name %>
    <br>
    <%= f.select :panel_name, options_for_select(Feature.panel_names.keys) %>
  </div> 

  <div class="form-group">
    <%= f.label :file %>
    <br>
    <%= f.file_field :file %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <br>
    <%= f.select :status, options_for_select(Feature.statuses.keys) %>
  </div> 
    
  <div class="form-group">
    Users: <%= select_tag("users[]", options_for_select(@users.map { |ff| [ff.name, ff.id] }, @feature.users.map { |fs| fs.id }),
      {:multiple=>true, :id => "users" }) %>
  </div>

  <div class="form-group">
    <%= f.submit("Save",class: "btn btn-success btn-lg") %>
  </div>
<% end %>
<%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/css/bootstrap-multiselect.min.css" %>
<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/js/bootstrap-multiselect.min.js" %>
<%= javascript_include_tag 'multiple.js' %>

app/views/features/new.html.erb
<%= render 'form' %>

app/views/features/show.html.erb
<div class="card m-3 p-3">
    Title: <%= @feature.title %>
    <br>
    <br>
    Description: <%= @feature.description %>
    <br>
    <br>
    Ticket Id: <%= @feature.ticket_id %>
    <br>
    <br>
    Status: <%= @feature.status %>
    <br>
    <br>
    Panel: <%= @feature.panel_name %>
    <br>
    <br>
    Project_id: <%= @feature.project_id %>
    <br>
    <br>
    Users: <%= h @feature.users.collect {|r| r.name}.join(', ') %>
    <%= link_to  "Download", @feature.file if @feature.file.attached?%>
    <div>
      <%= link_to  "edit", edit_project_feature_path(@project, @feature), class: "btn btn-outline-dark" %>
      <%= link_to 'destroy', [@project, @feature], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
</div>




<div>
  <h1>Tasks (<%= @tasks.completed.count%>/<%= @tasks.count %>)</h1>
  <% @tasks.each do |task| %>
    <% if task.status %>
      <strike>
        <%= task.description %>
      </strike>
    <% else %>
      <%= task.description %>
    <% end %>
    <br>
    <%= form_for task, validate: true do |f| %>
      <%= f.check_box :status, value: task.status %>
      <%= f.text_field :description, placeholder: "Edit task" %>
      <% if task.status %>
        <%= f.submit("Undo", class: "btn btn-primary") %>
      <% else %>
        <%= f.submit("Done", class: "btn btn-primary") %>
      <% end %>
    <% end %>
    <%= link_to 'destroy', task , method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %> 
    <br>   
  <% end %>
  <br>
    
</div>
<br>
<br>

<div>
  <%= form_for @task, validate: true do |f| %>
    <% if @task.errors.any? %>
      <h2>Errors: </h2>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>  
    <% end %>
    <p><%= f.text_field :description, placeholder: "Enter your task" %></p>
    <%= f.hidden_field :feature_id, value: @feature.id  %>
    <%= f.submit("Add Task", class: "btn btn-primary") %>
  <% end %>
</div>

<br>
<br>

<div>
  <h5>Comments</h5>
  <% @comments.each do |comment| %>
      <b><%= comment.user.name %></b>:
      <br>
      <%= comment.comment.to_s.tr('@','') %>
      <% if current_user == comment.user %>
        <%= link_to 'edit', edit_comment_path(comment) %>
        <%= link_to 'delete', comment , method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
      <% end %>
      <br>
  <% end %>
</div>

<div>
  <%= form_for @comment, validate: true do |f| %>
    <% if @comment.errors.any? %>
      <h2>Errors: </h2>
      <ul>
          <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>  
    <% end %>
    <p><%= f.text_field :comment, placeholder: "Enter your comment", class: "mention" %></p>
    <%= f.hidden_field :feature_id, value: @feature.id  %>
    <%= f.hidden_field :user_id, value: session[:user_id]  %>
    <%= f.submit("Add Comment", class: "btn btn-primary") %>
  <% end %>
</div>




<%= javascript_tag do %>
  x = <%= @usernames %>
<% end %>
<%= javascript_include_tag 'mention.js' %>